version: '3'
services:

  nifi:
    image: apache/nifi
    environment:
      NIFI_WEB_HTTP_PORT: '9090'
      NIFI_WEB_HTTP_HOST: '127.0.0.1'
    volumes:
      - './test/nifi-test-nar/target/nifi-test-nar-1.0-SNAPSHOT.nar:/opt/nifi/nifi-1.6.0/lib/test.nar'
        # Enable debug at 8000
      - './bootstrap.conf:/opt/nifi/nifi-1.6.0/conf/bootstrap.conf'
    network_mode: "host"

  nifi-registry:
    image: apache/nifi-registry
    environment:
      NIFI_REGISTRY_WEB_HTTP_PORT: '19090'
      NIFI_REGISTRY_WEB_HTTP_HOST: '127.0.0.1'
    network_mode: "host"

  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://qrowd-project.eu/"
    volumes:
      - ./projects/airports/rdf:/data/toLoad
    network_mode: "host"
