version: '3'
services:
  nifi:
    image: apache/nifi
    environment:
      NIFI_WEB_HTTP_PORT: '9090'
    volumes:
      - './nifi-data/:/home/nifi/data'
    network_mode: "host"
  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://qrowd-project.eu/"
    volumes:
      - ./projects/airports/rdf:/data/toLoad
    network_mode: "host"
